author:
  facebook: "https://facebook.com/example"
  twitter: " https://twitter.com/example"
  email: "contact@example.com"
  name: "Acme Corporation"
  location: Mezel
  phone: (999) 999-9999
  hours: "Mon-Fri: 9:00AM - 6:00PM, ET"
